plugins {
    alias(libs.plugins.android.application)
}

def localProps = new Properties()
def localPropsFile = rootProject.file("local.properties")
if (localPropsFile.exists()) {
    localProps.load(new FileInputStream(localPropsFile))
}

def gradleProps = new Properties()
def gradlePropsFile = rootProject.file("gradle.properties")
if (gradlePropsFile.exists()){
    gradleProps.load(new FileInputStream(gradlePropsFile))
}

android {
    namespace 'com.github.borz7zy.telegramm'
    compileSdk 36

    defaultConfig {
        applicationId "com.github.borz7zy.telegramm"
        minSdk 33
        targetSdk 36
        versionCode gradleProps.getProperty("app.versionCode").toInteger()
        versionName gradleProps.getProperty("app.version").toString()
        resValue "string", "api_id",
                localProps.getProperty("api_id", "")
        resValue "string", "api_hash",
                localProps.getProperty("api_hash", "")
        def testDc = localProps.getProperty("test_dc", "false").toBoolean()
        resValue "bool", "test_dc", testDc.toString()
        resValue "string", "version_code",
                gradleProps.getProperty("app.versionCode", "1")
        resValue "string", "version_name",
                gradleProps.getProperty("app.version", "0.0.0")


        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        defaultSignKey {
            storeFile file("../keystore/public.keystore")
            storePassword "123456"
            keyAlias "tgm-public-key"
            keyPassword "123456"
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.getByName("defaultSignKey")
        }
        debug {
            signingConfig = signingConfigs.getByName("defaultSignKey")
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.recyclerview
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata
    implementation libs.lifecycle.viewmodel
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.fragment
    implementation libs.preference

    implementation 'androidx.lifecycle:lifecycle-runtime:2.10.0'

    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.dynamicanimation:dynamicanimation:1.0.0'
    implementation 'com.github.massoudss:waveformSeekBar:5.0.2'
    implementation 'com.github.lincollincol:amplituda:2.2.2'

    implementation project(':rlottie')
    implementation project(':ffmpeg')

    implementation 'com.github.bumptech.glide:glide:5.0.5'
    implementation libs.legacy.support.v4
    annotationProcessor 'com.github.bumptech.glide:compiler:5.0.5'

    implementation project(':SlidingMenu')
    implementation project(':LibMonet')
    implementation project(':tdlib')

    implementation 'androidx.room:room-runtime:2.8.4'
    annotationProcessor 'androidx.room:room-compiler:2.8.4'

    implementation 'androidx.paging:paging-runtime:3.4.1'
}