name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Check gradlew
        shell: powershell
        run: |
          if (-Not (Test-Path "gradlew.bat")) {
            Write-Error "gradlew.bat not found!"
            exit 1
          }

      - name: Build Debug and Release
        shell: powershell
        run: .\gradlew.bat clean assembleDebug assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/**/debug/*.apk
          if-no-files-found: error

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/**/release/*.apk
          if-no-files-found: warn

  telegram:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo for git log
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Debug Artifact
        uses: actions/download-artifact@v4
        with:
          name: debug-apk
          path: apk

      - name: Send to Telegram
        env:
          TG_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TG_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
        run: |
          APK_PATH=$(find apk -name "*.apk" | head -n 1)

          if [ -z "$APK_PATH" ]; then
            echo "APK not found"
            exit 1
          fi

          BRANCH="${GITHUB_REF_NAME}"
          
          COMMIT_MESSAGES=$(git log -n 10 --pretty=format:"- %s")

          CAPTION="New Android Build from branch: *$BRANCH*. Commits:%0A$COMMIT_MESSAGES"
          
          if [ ${#CAPTION} -gt 1000 ]; then
             CAPTION="${CAPTION:0:1000}... (truncated)"
          fi
          
          curl -v -F "chat_id=$TG_CHAT_ID" \
          -F "message_thread_id=$TG_TOPIC_ID" \
          -F "document=@$APK_PATH" \
          -F "caption=$CAPTION" \
          "https://api.telegram.org/bot$TG_TOKEN/sendDocument"
